org.gradle.jvmargs=-Xmx2048M
enabled_platforms=fabric,neoforge
mod_id=exposure_catalog
archives_name=exposure_catalog
mod_name=Exposure Catalog
mod_version=1.1.0
mod_release_type=release
mod_license=MIT
maven_group=io.github.mortuusars.exposure_catalog
mod_authors=mortuusars
mod_description=Creative-mode tool to view and manage exposures
mod_page=https://www.curseforge.com/minecraft/mc-mods/exposure-catalog
mod_github=https://github.com/mortuusars/exposure_catalog
mod_issues=https://github.com/mortuusars/exposure_catalog/issues
mod_curseforge_project_id=1023882
mod_modrinth_project_id=PWcQ3kcp
# Base
minecraft_version=1.21.1
minecraft_version_range=[1.21,)
supported_minecraft_versions=1.21,1.21.1
parchment_version=1.21:2024.07.28
# Fabric
fabric_loader_version=0.16.9
fabric_api_version=0.102.1+1.21.1
# NeoForge
neoforge_version=21.1.83
neoforge_version_range=[21,)
neoforge_loader_version_range=[4,)
jade_neoforge_id=6155158
realcamera_neoforge_id=5426903
# Dependencies
exposure_version=1.8.4
required_exposure_version_range_forge=[1.8.4,)
required_exposure_version_range_fabric=>=1.8.4
forge_config_api_port_version=21.1.0
jei_version=19.19.0.220
luckperms_api_version=5.4
jupiterVersion=5.11.3