org.gradle.jvmargs=-Xmx2048M
enabled_platforms=fabric,forge
# Mod
mod_id=exposure_catalog
archives_name=exposure_catalog
mod_name=Exposure Catalog
mod_version=1.1.1
mod_release_type=release
mod_license=MIT
maven_group=io.github.mortuusars.exposure_catalog
mod_authors=mortuusars
mod_description=Creative-mode tool to view and manage exposures
mod_page=https://www.curseforge.com/minecraft/mc-mods/exposure-catalog
mod_github=https://github.com/mortuusars/exposure_catalog
mod_issues=https://github.com/mortuusars/exposure_catalog/issues
mod_curseforge_project_id=1023882
mod_modrinth_project_id=PWcQ3kcp
# Base
minecraft_version=1.20.1
minecraft_version_range=[1.20,)
supported_minecraft_versions=1.20,1.20.1
parchment_version=1.20.1:2023.09.03
# Fabric
fabric_loader_version=0.16.9
fabric_api_version=0.92.2+1.20.1
# Forge
forge_version=1.20.1-47.3.0
forge_version_range=[47,)
forge_loader_version_range=[4,)
jade_forge_id=6155158
# Dependencies
exposure_version=1.9.14
required_exposure_version_range_forge=[1.9.14,)
required_exposure_version_range_fabric=>=1.9.14
forge_config_api_port_version=8.0.1
jei_version=15.20.0.112
jupiterVersion=5.11.3
luckperms_api_version=5.4